from django.contrib import admin
from simple_history.admin import SimpleHistoryAdmin

from players.models import *

# Admin interface
admin.site.register(Character, SimpleHistoryAdmin)
admin.site.register(Discipline, SimpleHistoryAdmin)
admin.site.register(DisciplineRating, SimpleHistoryAdmin)
admin.site.register(Attribute, SimpleHistoryAdmin)
admin.site.register(AttributeRating, SimpleHistoryAdmin)

admin.site.register(Equipment, SimpleHistoryAdmin)
admin.site.register(Ghoul, SimpleHistoryAdmin)
admin.site.register(Title, SimpleHistoryAdmin)
admin.site.register(CanonFact, SimpleHistoryAdmin)
admin.site.register(PoliticalFaction, SimpleHistoryAdmin)
admin.site.register(Boon, SimpleHistoryAdmin)
admin.site.register(Relationship, SimpleHistoryAdmin)
admin.site.register(Age, SimpleHistoryAdmin)
admin.site.register(Hook, SimpleHistoryAdmin)
admin.site.register(HookAttribute, SimpleHistoryAdmin)
admin.site.register(Nature, SimpleHistoryAdmin)
admin.site.register(Specialization, SimpleHistoryAdmin)
admin.site.register(Ritual, SimpleHistoryAdmin)
admin.site.register(RitualRating, SimpleHistoryAdmin)
admin.site.register(ActionType, SimpleHistoryAdmin)
admin.site.register(Action, SimpleHistoryAdmin)
admin.site.register(Domain, SimpleHistoryAdmin)
admin.site.register(Session, SimpleHistoryAdmin)
admin.site.register(Feeding, SimpleHistoryAdmin)
admin.site.register(ActiveDisciplines, SimpleHistoryAdmin)
admin.site.register(InfluenceRating, SimpleHistoryAdmin)
admin.site.register(Population, SimpleHistoryAdmin)
admin.site.register(Influence, SimpleHistoryAdmin)
admin.site.register(Clan, SimpleHistoryAdmin)
admin.site.register(ActionOption, SimpleHistoryAdmin)
admin.site.register(ExtraAction, SimpleHistoryAdmin)
admin.site.register(Rumor, SimpleHistoryAdmin)

admin.site.register(ElderPower, SimpleHistoryAdmin)
admin.site.register(Weapon, SimpleHistoryAdmin)
admin.site.register(AidAction, SimpleHistoryAdmin)
admin.site.register(ConserveInfluence, SimpleHistoryAdmin)
admin.site.register(ConserveDomain, SimpleHistoryAdmin)
admin.site.register(InfluenceForge, SimpleHistoryAdmin)
admin.site.register(InfluenceSteal, SimpleHistoryAdmin)
admin.site.register(InfluenceDestroy, SimpleHistoryAdmin)
admin.site.register(InvestigateCharacterInfluence, SimpleHistoryAdmin)
admin.site.register(InvestigateCharacterResources, SimpleHistoryAdmin)
admin.site.register(InvestigateCharacterDowntimeActions, SimpleHistoryAdmin)
admin.site.register(InvestigateCounterSpionage, SimpleHistoryAdmin)
admin.site.register(InvestigatePhenomenon, SimpleHistoryAdmin)
admin.site.register(InvestigateInfluence, SimpleHistoryAdmin)
admin.site.register(LearnDiscipline, SimpleHistoryAdmin)
admin.site.register(LearnAttribute, SimpleHistoryAdmin)
admin.site.register(LearnSpecialization, SimpleHistoryAdmin)
admin.site.register(InvestGhoul, SimpleHistoryAdmin)
admin.site.register(InvestEquipment, SimpleHistoryAdmin)
admin.site.register(InvestWeapon, SimpleHistoryAdmin)
admin.site.register(InvestHerd, SimpleHistoryAdmin)
admin.site.register(InvestHaven, SimpleHistoryAdmin)
admin.site.register(Rest, SimpleHistoryAdmin)

admin.site.register(NeglectDomain, SimpleHistoryAdmin)
admin.site.register(PatrolDomain, SimpleHistoryAdmin)
admin.site.register(KeepersQuestion, SimpleHistoryAdmin)
admin.site.register(PrimogensQuestion, SimpleHistoryAdmin)
admin.site.register(PrimogensAidAction, SimpleHistoryAdmin)
    
admin.site.register(InfluencePriority, SimpleHistoryAdmin)
admin.site.register(ResourcePriority, SimpleHistoryAdmin)

admin.site.register(InfluenceList, SimpleHistoryAdmin)



