# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-13 16:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0011_auto_20170113_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=1)),
                ('exp', models.PositiveIntegerField(default=0)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Discipline')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplineRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=1)),
                ('exp', models.PositiveIntegerField(default=0)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Discipline')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAttributeRating',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=1)),
                ('exp', models.PositiveIntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('discipline', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='players.Discipline')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical attribute rating',
                'get_latest_by': 'history_date',
                'ordering': ('-history_date', '-history_id'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalDisciplineRating',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=1)),
                ('exp', models.PositiveIntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('discipline', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='players.Discipline')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical discipline rating',
                'get_latest_by': 'history_date',
                'ordering': ('-history_date', '-history_id'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalHook',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('influence', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='players.Influence')),
            ],
            options={
                'verbose_name': 'historical hook',
                'get_latest_by': 'history_date',
                'ordering': ('-history_date', '-history_id'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalHookAttribute',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical hook attribute',
                'get_latest_by': 'history_date',
                'ordering': ('-history_date', '-history_id'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalNature',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical nature',
                'get_latest_by': 'history_date',
                'ordering': ('-history_date', '-history_id'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalRitual',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.PositiveIntegerField(default=1)),
                ('description', models.TextField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical ritual',
                'get_latest_by': 'history_date',
                'ordering': ('-history_date', '-history_id'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalRitualRating',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('invested', models.PositiveIntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical ritual rating',
                'get_latest_by': 'history_date',
                'ordering': ('-history_date', '-history_id'),
            },
        ),
        migrations.CreateModel(
            name='Hook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HookAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Nature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ritual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.PositiveIntegerField(default=1)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RitualRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invested', models.PositiveIntegerField(default=0)),
                ('ritual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Ritual')),
            ],
        ),
        migrations.RemoveField(
            model_name='disciplinestat',
            name='discipline',
        ),
        migrations.RemoveField(
            model_name='historicaldisciplinestat',
            name='discipline',
        ),
        migrations.RemoveField(
            model_name='historicaldisciplinestat',
            name='history_user',
        ),
        migrations.AddField(
            model_name='character',
            name='SpecialExp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='Willpower',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='blood',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='exp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='goal1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='goal2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='goal3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='health',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='character',
            name='humanity',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='character',
            name='humanityExp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcharacter',
            name='SpecialExp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcharacter',
            name='Willpower',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcharacter',
            name='blood',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='historicalcharacter',
            name='exp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcharacter',
            name='goal1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalcharacter',
            name='goal2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalcharacter',
            name='goal3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalcharacter',
            name='health',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='historicalcharacter',
            name='humanity',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='historicalcharacter',
            name='humanityExp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='players.AttributeRating'),
        ),
        migrations.AlterField(
            model_name='character',
            name='disciplines',
            field=models.ManyToManyField(blank=True, to='players.DisciplineRating'),
        ),
        migrations.AlterField(
            model_name='character',
            name='resources',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalcharacter',
            name='resources',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='DisciplineStat',
        ),
        migrations.DeleteModel(
            name='HistoricalDisciplineStat',
        ),
        migrations.AddField(
            model_name='hook',
            name='attributes',
            field=models.ManyToManyField(to='players.HookAttribute'),
        ),
        migrations.AddField(
            model_name='hook',
            name='influence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Influence'),
        ),
        migrations.AddField(
            model_name='historicalritualrating',
            name='ritual',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='players.Ritual'),
        ),
        migrations.AddField(
            model_name='character',
            name='hooks',
            field=models.ManyToManyField(blank=True, to='players.Hook'),
        ),
        migrations.AddField(
            model_name='character',
            name='nature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Nature'),
        ),
        migrations.AddField(
            model_name='character',
            name='rituals',
            field=models.ManyToManyField(blank=True, to='players.RitualRating'),
        ),
        migrations.AddField(
            model_name='historicalcharacter',
            name='nature',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='players.Nature'),
        ),
    ]
