# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-13 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0014_auto_20170113_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalrelationship',
            old_name='char',
            new_name='otherCharacter',
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='char',
            new_name='otherCharacter',
        ),
    ]
