# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-13 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0015_auto_20170113_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalrelationship',
            old_name='otherCharacter',
            new_name='character1',
        ),
        migrations.RemoveField(
            model_name='character',
            name='relationships',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='otherCharacter',
        ),
        migrations.AddField(
            model_name='historicalrelationship',
            name='character2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='players.Character'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='character1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationship1', to='players.Character'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='character2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationship2', to='players.Character'),
        ),
        migrations.AlterField(
            model_name='ghoul',
            name='hook',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Hook'),
        ),
    ]
