# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-15 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20170115_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='influencedestroy',
            old_name='hook',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='influencesteal',
            old_name='hook',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='level',
        ),
        migrations.RemoveField(
            model_name='learn',
            name='level',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='level',
        ),
        migrations.AddField(
            model_name='character',
            name='hiddenGoalResult',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='openGoal1Result',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='openGoal2Result',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='weapons',
            field=models.ManyToManyField(blank=True, to='players.Weapon'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Specialization'),
        ),
        migrations.AddField(
            model_name='historicalcharacter',
            name='hiddenGoalResult',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalcharacter',
            name='openGoal1Result',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalcharacter',
            name='openGoal2Result',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='helpers',
            field=models.ManyToManyField(blank=True, related_name='allowedHelp', to='players.Character'),
        ),
        migrations.AlterField(
            model_name='aidaction',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='clan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Clan'),
        ),
        migrations.AlterField(
            model_name='character',
            name='nature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Nature'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='clanDisciplines',
            field=models.ManyToManyField(blank=True, to='players.Discipline'),
        ),
        migrations.AlterField(
            model_name='disciplinerating',
            name='elderPowers',
            field=models.ManyToManyField(blank=True, to='players.ElderPower'),
        ),
        migrations.AlterField(
            model_name='historicalaction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalritualrating',
            name='exp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hook',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='players.HookAttribute'),
        ),
        migrations.AlterField(
            model_name='investigatecharacterinfluence',
            name='priority1',
            field=models.CharField(blank=True, choices=[('Alla Masternivåer', 'Alla Masternivåer'), ('Alla Master och Contendernivåer', 'Alla Master och Contendernivåer'), ('Alla Inflytandenivåer', 'Alla Inflytandenivåer'), ('Namn på en hook i ett valt inflytande', 'Namn på en hook i ett valt inflytande'), ('En hooks keywords', 'En hooks keywords')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='investigatecharacterinfluence',
            name='priority2',
            field=models.CharField(blank=True, choices=[('Alla Masternivåer', 'Alla Masternivåer'), ('Alla Master och Contendernivåer', 'Alla Master och Contendernivåer'), ('Alla Inflytandenivåer', 'Alla Inflytandenivåer'), ('Namn på en hook i ett valt inflytande', 'Namn på en hook i ett valt inflytande'), ('En hooks keywords', 'En hooks keywords')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='investigatecharacterinfluence',
            name='priority3',
            field=models.CharField(blank=True, choices=[('Alla Masternivåer', 'Alla Masternivåer'), ('Alla Master och Contendernivåer', 'Alla Master och Contendernivåer'), ('Alla Inflytandenivåer', 'Alla Inflytandenivåer'), ('Namn på en hook i ett valt inflytande', 'Namn på en hook i ett valt inflytande'), ('En hooks keywords', 'En hooks keywords')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='investigatecharacterinfluence',
            name='priority4',
            field=models.CharField(blank=True, choices=[('Alla Masternivåer', 'Alla Masternivåer'), ('Alla Master och Contendernivåer', 'Alla Master och Contendernivåer'), ('Alla Inflytandenivåer', 'Alla Inflytandenivåer'), ('Namn på en hook i ett valt inflytande', 'Namn på en hook i ett valt inflytande'), ('En hooks keywords', 'En hooks keywords')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='investigatecharacterinfluence',
            name='priority5',
            field=models.CharField(blank=True, choices=[('Alla Masternivåer', 'Alla Masternivåer'), ('Alla Master och Contendernivåer', 'Alla Master och Contendernivåer'), ('Alla Inflytandenivåer', 'Alla Inflytandenivåer'), ('Namn på en hook i ett valt inflytande', 'Namn på en hook i ett valt inflytande'), ('En hooks keywords', 'En hooks keywords')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='investigatecharacterinfluence',
            name='priority6',
            field=models.CharField(blank=True, choices=[('Alla Masternivåer', 'Alla Masternivåer'), ('Alla Master och Contendernivåer', 'Alla Master och Contendernivåer'), ('Alla Inflytandenivåer', 'Alla Inflytandenivåer'), ('Namn på en hook i ett valt inflytande', 'Namn på en hook i ett valt inflytande'), ('En hooks keywords', 'En hooks keywords')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='investigatecharacterinfluence',
            name='priority7',
            field=models.CharField(blank=True, choices=[('Alla Masternivåer', 'Alla Masternivåer'), ('Alla Master och Contendernivåer', 'Alla Master och Contendernivåer'), ('Alla Inflytandenivåer', 'Alla Inflytandenivåer'), ('Namn på en hook i ett valt inflytande', 'Namn på en hook i ett valt inflytande'), ('En hooks keywords', 'En hooks keywords')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='investigatecharacterinfluence',
            name='priority8',
            field=models.CharField(blank=True, choices=[('Alla Masternivåer', 'Alla Masternivåer'), ('Alla Master och Contendernivåer', 'Alla Master och Contendernivåer'), ('Alla Inflytandenivåer', 'Alla Inflytandenivåer'), ('Namn på en hook i ett valt inflytande', 'Namn på en hook i ett valt inflytande'), ('En hooks keywords', 'En hooks keywords')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='investigatecharacterresources',
            name='priority1',
            field=models.CharField(blank=True, choices=[('En slumpmässig background', 'En slumpmässig background'), ('En vald typ av background', 'En vald typ av background'), ('Hur mycket blod som tagits och var', 'Hur mycket blod som tagits och var'), ('Hur många Resource points karaktären har', 'Hur många Resource points karaktären har')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='investigatecharacterresources',
            name='priority2',
            field=models.CharField(blank=True, choices=[('En slumpmässig background', 'En slumpmässig background'), ('En vald typ av background', 'En vald typ av background'), ('Hur mycket blod som tagits och var', 'Hur mycket blod som tagits och var'), ('Hur många Resource points karaktären har', 'Hur många Resource points karaktären har')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='investigatecharacterresources',
            name='priority3',
            field=models.CharField(blank=True, choices=[('En slumpmässig background', 'En slumpmässig background'), ('En vald typ av background', 'En vald typ av background'), ('Hur mycket blod som tagits och var', 'Hur mycket blod som tagits och var'), ('Hur många Resource points karaktären har', 'Hur många Resource points karaktären har')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='investigatecharacterresources',
            name='priority4',
            field=models.CharField(blank=True, choices=[('En slumpmässig background', 'En slumpmässig background'), ('En vald typ av background', 'En vald typ av background'), ('Hur mycket blod som tagits och var', 'Hur mycket blod som tagits och var'), ('Hur många Resource points karaktären har', 'Hur många Resource points karaktären har')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='investigatecharacterresources',
            name='priority5',
            field=models.CharField(blank=True, choices=[('En slumpmässig background', 'En slumpmässig background'), ('En vald typ av background', 'En vald typ av background'), ('Hur mycket blod som tagits och var', 'Hur mycket blod som tagits och var'), ('Hur många Resource points karaktären har', 'Hur många Resource points karaktären har')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='investigatecharacterresources',
            name='priority6',
            field=models.CharField(blank=True, choices=[('En slumpmässig background', 'En slumpmässig background'), ('En vald typ av background', 'En vald typ av background'), ('Hur mycket blod som tagits och var', 'Hur mycket blod som tagits och var'), ('Hur många Resource points karaktären har', 'Hur många Resource points karaktären har')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='investigatecharacterresources',
            name='priority7',
            field=models.CharField(blank=True, choices=[('En slumpmässig background', 'En slumpmässig background'), ('En vald typ av background', 'En vald typ av background'), ('Hur mycket blod som tagits och var', 'Hur mycket blod som tagits och var'), ('Hur många Resource points karaktären har', 'Hur många Resource points karaktären har')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='investigatecharacterresources',
            name='priority8',
            field=models.CharField(blank=True, choices=[('En slumpmässig background', 'En slumpmässig background'), ('En vald typ av background', 'En vald typ av background'), ('Hur mycket blod som tagits och var', 'Hur mycket blod som tagits och var'), ('Hur många Resource points karaktären har', 'Hur många Resource points karaktären har')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='character1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship1', to='players.Character'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='character2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship2', to='players.Character'),
        ),
        migrations.AlterField(
            model_name='ritualrating',
            name='exp',
            field=models.BooleanField(default=False),
        ),
    ]
