# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-16 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_auto_20170115_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigatecharacterinfluence',
            name='hook',
        ),
        migrations.RemoveField(
            model_name='investigatecharacterinfluence',
            name='influence',
        ),
        migrations.RemoveField(
            model_name='investigatecharacterresources',
            name='backgrounds',
        ),
        migrations.AddField(
            model_name='influencepriority',
            name='target',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='resourcepriority',
            name='target',
            field=models.CharField(blank=True, choices=[('weapon', 'weapon'), ('equipment', 'equipment'), ('ghouls', 'ghouls'), ('herd', 'herd'), ('haven', 'haven')], max_length=200),
        ),
    ]
