# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-16 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_auto_20170116_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='hiddenGoalResult',
        ),
        migrations.RemoveField(
            model_name='character',
            name='openGoal1Result',
        ),
        migrations.RemoveField(
            model_name='character',
            name='openGoal2Result',
        ),
        migrations.RemoveField(
            model_name='historicalcharacter',
            name='hiddenGoalResult',
        ),
        migrations.RemoveField(
            model_name='historicalcharacter',
            name='openGoal1Result',
        ),
        migrations.RemoveField(
            model_name='historicalcharacter',
            name='openGoal2Result',
        ),
        migrations.AlterField(
            model_name='activedisciplines',
            name='disciplines',
            field=models.ManyToManyField(blank=True, to='players.DisciplineRating'),
        ),
    ]
