# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-16 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_auto_20170116_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='rumor',
            name='canonFact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.CanonFact'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.DisciplineRating'),
        ),
        migrations.AlterField(
            model_name='historicalfeeding',
            name='discipline',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='players.DisciplineRating'),
        ),
        migrations.AlterField(
            model_name='rumor',
            name='influence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Influence'),
        ),
    ]
