# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_auto_20160216_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rumor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reliable', models.BooleanField()),
                ('description', models.TextField()),
                ('gm_note', models.TextField(blank=True)),
                ('influence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Influence')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Character')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rumors', to='players.Session')),
            ],
        ),
    ]
