# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-19 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_auto_20170116_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnAttribute',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='players.Action')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Attribute')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AttributeTrainee', to='players.Character')),
            ],
            bases=('players.action',),
        ),
        migrations.CreateModel(
            name='LearnDiscipline',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='players.Action')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Discipline')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DisciplineTrainee', to='players.Character')),
            ],
            bases=('players.action',),
        ),
        migrations.CreateModel(
            name='LearnSpecialization',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='players.Action')),
                ('newSpecialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner', to='players.Specialization')),
                ('oldSpecialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forgeter', to='players.Specialization')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SpecializationTrainee', to='players.Character')),
            ],
            bases=('players.action',),
        ),
        migrations.RemoveField(
            model_name='learn',
            name='action_ptr',
        ),
        migrations.RemoveField(
            model_name='learn',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='influencepriority',
            name='target',
        ),
        migrations.RemoveField(
            model_name='resourcepriority',
            name='target',
        ),
        migrations.AddField(
            model_name='influencepriority',
            name='influence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Influence'),
        ),
        migrations.AddField(
            model_name='investigatecharacterinfluence',
            name='hooks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='investigatecharacterresources',
            name='hooks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='investghoul',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Discipline'),
        ),
        migrations.DeleteModel(
            name='Learn',
        ),
    ]
