# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-19 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_auto_20170119_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='influenceforge',
            old_name='inflytande',
            new_name='influence',
        ),
    ]
