# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-19 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_auto_20170119_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorAttribute',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='players.Action')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Attribute')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_teacher', to='players.Character')),
            ],
            bases=('players.action',),
        ),
        migrations.CreateModel(
            name='MentorDiscipline',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='players.Action')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Discipline')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_teacher', to='players.Character')),
            ],
            bases=('players.action',),
        ),
        migrations.CreateModel(
            name='MentorSpecialization',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='players.Action')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Specialization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialization_teacher', to='players.Character')),
            ],
            bases=('players.action',),
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='action_ptr',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='student',
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
    ]
