# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-19 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_auto_20170119_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigatecharacterresources',
            name='hooks',
        ),
    ]
