# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-19 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_remove_investigatecharacterresources_hooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeepersQuestion',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='players.Action')),
                ('question', models.TextField()),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Character')),
            ],
            bases=('players.action',),
        ),
        migrations.CreateModel(
            name='NeglectDomain',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='players.Action')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Domain')),
            ],
            bases=('players.action',),
        ),
        migrations.CreateModel(
            name='PatrolDomain',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='players.Action')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Domain')),
            ],
            bases=('players.action',),
        ),
        migrations.CreateModel(
            name='PrimogensAidAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='players.Action')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('betrayal', models.BooleanField(default=False)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.ActionType')),
                ('helpee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primogen_help', to='players.Character')),
            ],
            bases=('players.action',),
        ),
        migrations.CreateModel(
            name='PrimogensQuestion',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='players.Action')),
                ('question', models.TextField()),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Character')),
            ],
            bases=('players.action',),
        ),
    ]
