# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-20 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0015_auto_20170120_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbond',
            name='master',
        ),
        migrations.RemoveField(
            model_name='character',
            name='bloodBond',
        ),
        migrations.DeleteModel(
            name='BloodBond',
        ),
    ]
