# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-20 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0017_character_relationships'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='canonFact',
            new_name='canon_fact',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='humanityExp',
            new_name='humanity_exp',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='openGoal',
            new_name='open_Goal',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='politicalFraction',
            new_name='political_faction',
        ),
        migrations.RenameField(
            model_name='historicalcharacter',
            old_name='humanityExp',
            new_name='humanity_exp',
        ),
        migrations.RenameField(
            model_name='historicalcharacter',
            old_name='openGoal',
            new_name='open_Goal',
        ),
        migrations.RenameField(
            model_name='historicalcharacter',
            old_name='politicalFraction',
            new_name='political_faction',
        ),
    ]
