# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-20 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0018_auto_20170120_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='open_Goal',
            new_name='open_goal',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='SpecialExp',
            new_name='special_exp',
        ),
        migrations.RenameField(
            model_name='historicalcharacter',
            old_name='open_Goal',
            new_name='open_goal',
        ),
        migrations.RenameField(
            model_name='historicalcharacter',
            old_name='SpecialExp',
            new_name='special_exp',
        ),
    ]
