# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-20 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0019_auto_20170120_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='hiddenGoal1',
            new_name='hidden_goal1',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='hiddenGoal2',
            new_name='hidden_goal2',
        ),
        migrations.RenameField(
            model_name='historicalcharacter',
            old_name='hiddenGoal1',
            new_name='hidden_goal1',
        ),
        migrations.RenameField(
            model_name='historicalcharacter',
            old_name='hiddenGoal2',
            new_name='hidden_goal2',
        ),
    ]
