# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-20 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0020_auto_20170120_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributerating',
            old_name='elderBlood',
            new_name='elder_blood',
        ),
        migrations.RenameField(
            model_name='clan',
            old_name='clanDisciplines',
            new_name='clan_disciplines',
        ),
        migrations.RenameField(
            model_name='historicalattributerating',
            old_name='elderBlood',
            new_name='elder_blood',
        ),
        migrations.RenameField(
            model_name='historicalweapon',
            old_name='damageType',
            new_name='damage_type',
        ),
        migrations.RenameField(
            model_name='weapon',
            old_name='damageType',
            new_name='damage_type',
        ),
    ]
