# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-20 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0022_auto_20170120_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='Willpower',
            new_name='willpower',
        ),
        migrations.RenameField(
            model_name='historicalcharacter',
            old_name='Willpower',
            new_name='willpower',
        ),
    ]
