# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-20 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0023_auto_20170120_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='hidden_goal2',
            new_name='hidden_goal',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='open_goal',
            new_name='open_goal1',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='hidden_goal1',
            new_name='open_goal2',
        ),
        migrations.RenameField(
            model_name='historicalcharacter',
            old_name='hidden_goal2',
            new_name='hidden_goal',
        ),
        migrations.RenameField(
            model_name='historicalcharacter',
            old_name='open_goal',
            new_name='open_goal1',
        ),
        migrations.RenameField(
            model_name='historicalcharacter',
            old_name='hidden_goal1',
            new_name='open_goal2',
        ),
    ]
