# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-20 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0024_auto_20170120_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalcharacter',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalsession',
            name='is_initial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='is_initial',
            field=models.BooleanField(default=False),
        ),
    ]
