# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-20 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0025_auto_20170120_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsession',
            old_name='is_initial',
            new_name='is_special',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='is_initial',
            new_name='is_special',
        ),
        migrations.AddField(
            model_name='historicalsession',
            name='action_set',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='players.ActionOption'),
        ),
        migrations.AddField(
            model_name='session',
            name='action_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.ActionOption'),
        ),
    ]
