# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-22 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0027_influencelist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalPoliticalFraction',
            new_name='HistoricalPoliticalFaction',
        ),
        migrations.RenameModel(
            old_name='PoliticalFraction',
            new_name='PoliticalFaction',
        ),
        migrations.AlterModelOptions(
            name='historicalpoliticalfaction',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical political faction'},
        ),
    ]
